Features branch pull request
azizunnabi/portfolio-mobile-finish pull request #1
Opened 2022-08-20 16:14 UTC by azizunnabi

This pull request is creating to check for linters html and css errors

2022-08-20 16:44 UTC, sja-thedude requested changes
## Required Changes ♻️

Hi @azizunnabi, This is @sja-thedude your code reviewer.

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![200w](https://user-images.githubusercontent.com/70269507/159484303-3187dacc-4a82-4263-bb1a-8d72417ce1d9.gif)

 ## Highlights
✔️ Good job so far

 ## Required Changes ♻️
- [ ] Kindly make sure to implement all the changes asked by the previous reviewer [here](https://github.com/azizunnabi/PORT-MOB-PROJ/pull/1#discussion_r950605006)
- [ ] Make sure to implement all the changes asked as the margin, colour, font size, button size etc.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me [@sja-thedude] in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-20 19:04 UTC, tresorsawasawa requested changes
# STATUS: REQUIRED CHANGES :recycle::recycle: 

Hi @azizunnabi 
Good job so far! I know you worked hard to implement this project, I really appreciate the effort you put in! But there are some issues that you still need to work on to go to the next project but you are almost there! 

![almost-there](https://user-images.githubusercontent.com/57562869/143511358-9cde7daf-4ad0-4db2-8f15-18b54288ff91.gif)

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Your design looks good :100: :heavy_check_mark: 
- Good PR description :heavy_check_mark: 
- Follow GitHub flow :heavy_check_mark: 

## Required changes :recycle: :recycle: 
- [ ] Check the comments under the review.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear. 
Please ping me [@tresorsawasawa](https://github.com/tresorsawasawa) when you comment so I can receive the notification or use slack with the same name._

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-20 19:04 UTC, tresorsawasawa commented on index.html
> +
- [ **OPTIONAL** ] Kindly make sure you remove all the empty space lines in your code base to make your code cleaner and for best practices.

2022-08-20 19:04 UTC, tresorsawasawa commented on index.html
> +          <h5 class="ets" >ETS CONNECT</h5>
- [ **OPTIONAL** ] **RECOMMENDED:** Kindly make sure you correct this typo error where you write **"ETS CONNECT"** instead of **"LET'S CONNECT"** to make your project professioanal

2022-08-20 19:04 UTC, tresorsawasawa commented on index.html
> +          <li><img src="images/angellist.PNG" alt="abc" class="lsls"></li>
- [ **OPTIONAL** ] **RECOMMENDED:** Kindly make sure each social media icon is a link(i.e each icon should be wrapped in a `<a>` tag) as it was required for your previous projects.

2022-08-20 19:04 UTC, tresorsawasawa commented on index.html
> +
- [ ] As mentioned by the previous reviewer, kindly make sure your project design sticks as much as possible to your chosen template. You are supposed to use the correct margins/paddings, color, font size, button size && interactions, **fixing the broken images,...**

| Figma Design | Your DEsign |
| ----------------- | ------------------- |
| ![about_section_1](https://user-images.githubusercontent.com/83042742/185762455-f4f26dd3-eb9f-4f12-bfc8-82952205eaaf.png) | ![Screenshot from 2022-08-20 20-49-47](https://user-images.githubusercontent.com/83042742/185762461-1182aca6-de84-4867-ba31-76fcd281b230.png) |

2022-08-21 05:24 UTC, emmiiorji approved these changes
Hi @azizunnabi , 

# Status: Approved ✅

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![congratulations](https://user-images.githubusercontent.com/20554583/185776842-20c4434b-7d45-4dc8-8e84-46fa28e1ba63.gif)


## Highlights
- Linter checks are passing
- Meaningful commit messages
- Proper use of GitHub flow

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-21 09:09 UTC, merged